[colors]
kraken_deep_sea_blue = [0, 22, 40]
kraken_ice_blue = [153, 217, 217]
kraken_boundless_blue = [53, 84, 100]
kraken_shadow_blue = [104, 162, 185]
kraken_red_alert = [233, 7, 43]
Mopo_darkest = [10, 10, 70]
Mopo_dark = [9, 9, 124]
Mopo_light = [0, 88, 143]
Mopo_lightest = [102, 177, 206]
SFC_grenat = [133, 20, 43]
GSHC_grenat = [109, 30, 48]
GSHC_gold = [255, 211, 0]
TNO_white = [255, 255, 255]
TNO_ink = [0, 3, 10]
TNO_dark_blue = [0, 36, 132]
TNO_blue = [18, 62, 183]
TNO_gray = [240, 243, 250]
TNO_action_blue = [51, 105, 255]
TNO_action_orange = [245, 113, 24]
TNO_sustainable_green = [46, 163, 57]
TNO_digital_blue = [102, 190, 204]
TNO_safe_purple = [141, 112, 204]
TNO_healthy_yellow = [245, 200, 20]
TNO_light_orange = [255, 169, 112]
